services:
  app:
    build: .
    image: telr-exchange
    container_name: telr-exchange
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    #   - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    environment:
      - AUTH_KEY=${AUTH_KEY}
      - AUTH_ENDPOINT=${AUTH_ENDPOINT}
      - SESSION_ENDPOINT=${SESSION_ENDPOINT}
