version: '3.7'

services:
  app:
    build: .
    image: telr-exchange
    container_name: telr-exchange
    restart: always
    ports:
      - '127.0.0.1:3000:3000'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
