<template>
    <f7-page>
        hi there, i'm onboarding!
    </f7-page>
</template>

<script>
import {
    f7Page,
    // f7Block,
    // f7Button,
    // f7Fab,
    // f7FabButton,
    // f7FabButtons,
    // f7Icon,
    // f7Link,
    // f7List,
    // f7ListButton,
    // f7ListInput,
    // f7ListItem,
    // f7Navbar,
    // f7NavLeft,
    // f7NavTitle,
    // f7NavTitleLarge,
    // f7NavRight,
    // f7Searchbar,
    // f7Tab,
    // f7Tabs,
    // f7Toolbar,
    // f7Card,
    // f7CardHeader,
    // f7CardContent,
    // f7CardFooter,
    // f7LoginScreen,
    // f7LoginScreenTitle,
    // f7BlockHeader,
    // f7BlockTitle,
    // f7BlockFooter,
} from 'framework7-vue'

export default {
    components: {
        f7Page,
        // f7Block,
        // f7Button,
        // f7Fab,
        // f7FabButton,
        // f7FabButtons,
        // f7Icon,
        // f7Link,
        // f7List,
        // f7ListButton,
        // f7ListInput,
        // f7ListItem,
        // f7Navbar,
        // f7NavLeft,
        // f7NavTitle,
        // f7NavTitleLarge,
        // f7NavRight,
        // f7Searchbar,
        // f7Tab,
        // f7Tabs,
        // f7Toolbar,
        // f7Card,
        // f7CardHeader,
        // f7CardContent,
        // f7CardFooter,
        // f7LoginScreen,
        // f7LoginScreenTitle,
        // f7BlockHeader,
        // f7BlockTitle,
        // f7BlockFooter,
    },
}
</script>
